FROM golang:1.21-alpine AS builder

WORKDIR /app

# Install required build tools
RUN apk add --no-cache git=2.47.1

# Copy go mod files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api

FROM alpine:3.18

WORKDIR /app

# Copy the binary from builder
COPY --from=builder /app/main .

# Copy SSL certificates if you're using HTTPS
# COPY cert.pem key.pem ./

# Create a non-root user
RUN adduser -D appuser
USER appuser

# Expose the port for application
EXPOSE 443

CMD ["./main"]
