FROM node:16-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY .. .

RUN npm run build

FROM node:16-alpine AS development

WORKDIR /app

COPY package*.json ./

RUN npm install --only=development

COPY --from=build /app/dist ./dist
COPY --from=build /app/public ./public

EXPOSE 3030

CMD ["npm", "run", "start:dev"]
